name: Run Jest tests in week1 folder

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd week-2/Week-2-Assignments/02-nodejs
          npm install 
          npm install jest 
          npx jest
               
#       - name: Run tests
#         run: |
#           cd week-3/01-reconciler
#           for folder in *; do
#             if [ -f "$folder/.test.js" ]; then
#               echo "Running tests in $folder"
#               npx jest
#             fi
#           done
