name: Run Jest tests in week1 folder

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd week-3/01-reconciler
          npm install 
          cd ..
          cd 02-course-app-easy
          npm install 
          cd ..
          cd 02-course-app-easy-2
          npm install 
          cd ..
          cd 03-course-app-medium
          npm install
          cd ..
          cd 04-course-app-hard
          npm install 
          cd ..
          npm install jest 
          npx jest
               
#       - name: Run tests
#         run: |
#           cd week-3/01-reconciler
#           for folder in *; do
#             if [ -f "$folder/.test.js" ]; then
#               echo "Running tests in $folder"
#               npx jest
#             fi
#           done
