name: Run Jest

on:
  pull_request:
  workflow_dispatch:

jobs:
  Week3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd week-3/01-reconciler
          npm install && npm install jest express 
          cd ..
          cd 02-course-app-easy
          npm install && npm install jest express
          cd ..
          cd 02-course-app-easy-2
          npm install && npm install jest express
          cd ..
          cd 03-course-app-medium
          npm install && npm install jest express
          cd ..
          cd 04-course-app-hard
          npm install && npm install jest express
          

      - name: Run tests
        run: |
          cd week-3
          npx jest --testPathPattern='src/**/*.[jt]s?(x)'


