name: Run Jest

on:
  pull_request:
  workflow_dispatch:

jobs:
  Week3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd week-3
          npm install --prefix=. @01-reconciler/package.json
          npm install --prefix=. @02-course-app-easy/package.json
          npm install --prefix=. @02-course-app-easy-2/package.json
          npm install --prefix=. @03-course-app-medium/package.json
          npm install --prefix=. @04-course-app-hard/package.json
          npm install jest
          
          

      - name: Run tests
        run: |
          cd week-3
          npx jest


