name: Run Jest

on:
  pull_request:
  workflow_dispatch:

jobs:
  Week3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd week-2
          npm install jest
          for dir in */; do                                                                                            
          (cd "$dir" && npm i && npx jest)
          done
          
                  

#       - name: Run tests
#         run: |
#           cd week-2
#           for dir in */; do                                                                                            
#           (cd "$dir" && npx jest)
#           done


