name: Unit Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          cd Week-2-Assignments-main/Week-2-Assignments-main/02-nodejs
          npm install
          npm install jest express
          npx jest
