name: Run Jest

on:
  pull_request:
  workflow_dispatch:

jobs:
  Week3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd week-3
          npm install jest
          

      - name: Run tests
        run: |
          cd week-3
          npx jest


