name: Run Jest

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd week-3
          cd 01-reconciler
          npm install
          npm install jest express 

      - name: Run tests
        run: |
          cd week-3
          npx jest

